packages:
  - packages/*
  - examples

catalog:
  '@biomejs/biome': ^2.4.4
  '@changesets/cli': ^2.29.8
  '@clack/prompts': ^1.0.1
  '@inkjs/ui': ^2.0.0
  '@napi-rs/keyring': ^1.2.0
  '@node-rs/argon2': ^2.0.2
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/semantic-conventions': ^1.40.0
  '@scalar/openapi-parser': ^0.23.13
  '@types/node': ^25.3.2
  '@types/nodemailer': ^7.0.11
  '@types/react': ^19.2.14
  '@vitest/coverage-v8': ^4.0.18
  basic-ftp: ^5.2.0
  citty: ^0.1.6
  consola: ^3.4.2
  execa: ^9.6.1
  fast-xml-parser: ^5.4.1
  http-cookie-agent: ^6.0.8
  imapflow: ^1.2.10
  ink: ^6.8.0
  ink-testing-library: ^4.0.0
  jose: ^5.10.0
  msw: ^2.12.3
  nodemailer: ^7.0.13
  openid-client: ^6.8.2
  picocolors: ^1.1.1
  pino: ^10.3.1
  pino-pretty: ^13.1.3
  react: ^19.2.4
  tough-cookie: ^5.1.2
  tsup: ^8.5.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  undici: ^7.22.0
  valibot: ^1.2.0
  vite: ^7.3.1
  vitest: ^4.0.18
  yaml: ^2.8.2
  zod: ^4.3.6
