packages:
  - packages/*
  - examples

catalog:
  '@biomejs/biome': ^2.3.10
  '@clack/prompts': ^0.10.0
  citty: ^0.1.6
  consola: ^3.4.0
  '@types/nodemailer': ^7.0.4
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/semantic-conventions': ^1.28.0
  '@changesets/cli': ^2.29.4
  '@types/node': ^25.0.3
  '@vitest/coverage-v8': ^4.0.16
  basic-ftp: ^5.0.5
  fast-xml-parser: ^4.5.0
  http-cookie-agent: ^6.0.6
  imapflow: ^1.2.3
  jose: ^5.9.6
  nodemailer: ^7.0.12
  openid-client: ^6.1.3
  pino: ^10.1.0
  pino-pretty: ^13.1.3
  tough-cookie: ^5.0.0
  tsup: ^8.5.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  valibot: ^1.2.0
  vite: ^7.3.0
  vitest: ^4.0.16
  zod: ^4.1.13
